### ISSUE TITLE
关于使用summary和 full content的判断

### ISSUE THREAD

**Issue by dsj96** [wbbeyourself/SCM4LLMs#2]
我想问下关于如何判断是否对检索到memorys(比如k=3)执行summary的判断？
在论文[old version](https://arxiv.org/abs/2304.13343) Figure 5
![image](https://github.com/wbbeyourself/SCM4LLMs/assets/51779172/5682139b-fae9-4a00-a716-cd2bc1d8e8ea)

和[SCM_Paper_Draft.pdf](./SCM_Paper_Draft.pdf) Figure 6是不同的prompt,此处的{content}是已经summary过的多个memory的吗？单个memory超过800tokens、多个memory token超过2000分别是在那一步判断的呢？
![image](https://github.com/wbbeyourself/SCM4LLMs/assets/51779172/4982bf01-ecb7-430b-a408-b36762d64bb7)
感谢！

**Comment by wbbeyourself** [comment]
您好，感谢您对我们工作的关注。关于 prompt 以我们放在repo 中的这个版本为准（这个是更新的版本），因为匿名期的原因，暂时还无法更新到 arxiv。

另外，prompt 里的 content 既可以是 原文，也可以是 summary 。具体操作可以参考代码：core/chat.py 中的 judge_drop_or_summary 函数。

**Comment by dsj96** [comment]
收到，感谢回复！
